{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "decision.fullname" . }}-frontend
  labels:
    {{- $component := "frontend" }}
    {{- include "decision.componentLabels" (set . "component" $component) | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "decision.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
---
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "decision.fullname" . }}-backend
  labels:
    {{- $component := "backend" }}
    {{- include "decision.componentLabels" (set . "component" $component) | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "decision.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
